# GoReleaser configuration for dosu-cli
version: 2

project_name: dosu

before:
  hooks:
    # Download dependencies to cache
    - go mod download

builds:
  - main: ./cmd/dosu-cli
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Exclude uncommon platform combinations
    ignore:
      - goos: windows
        goarch: arm64
    # Strip debug info to reduce binary size
    ldflags:
      - -s -w

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Enhancements"
      regexp: "^.*enhancement[(\\w)]*:+.*$"
      order: 2
    - title: Other Changes
      order: 999

# Homebrew tap
homebrew_casks:
  - name: dosu
    repository:
      owner: dosu-ai
      name: homebrew-dosu
    homepage: https://github.com/dosu-ai/dosu-cli
    description: "Dosu CLI tool"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"

# Release configuration
release:
  github:
    owner: dosu-ai
    name: dosu-cli
  draft: false
  prerelease: auto
